name: filmu_nams
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  motion_tab_bar: ^2.0.4
  pattern_background: ^1.1.3
  intl: ^0.20.1
  google_fonts: ^6.2.1
  bordered_text: ^2.0.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  loading_animation_widget: ^1.3.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.1
  cloud_firestore: ^5.6.2
  provider: ^6.1.2
  indexed: ^0.0.8
  cached_network_image: ^3.4.1
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google.png
    - assets/facebook.png
    - assets/pulp_fiction.jpg
